development_portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('portfolio.urls')),
    url(r'^admin/', admin.site.urls),
]

portfolio/urls.py
from django.conf.urls import url

from . import views

app_name = 'portfolio'
urlpatterns = [
    # ex: /
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /document/5/
    url(r'^document/(?P<pk>[0-9]+)/$', views.DocumentView.as_view(), name='document'),
    # ex: /audio/5/
    url(r'^audio/(?P<pk>[0-9]+)/$', views.AudioView.as_view(), name='audio'),
]

portfolio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Blurb(models.Model):
    blurb_text = models.CharField(max_length=200)
    
class ItemDocument(models.Model):
    item_text = models.CharField(max_length=32)
    embed_text = models.CharField(max_length=60)
    pub_date = models.DateTimeField('date published')
    
class ItemAudio(models.Model):
    item_text = models.CharField(max_length=32)
    embed_text = models.CharField(max_length=60)
    pub_date = models.DateTimeField('date published')

portfolio/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
import random

# Create your views here.

from .models import Blurb, ItemDocument, ItemAudio

class IndexView(generic.ListView):
    template_name = 'portfolio/index.html'
    model = Blurb
    
    def get_context_data(self, **kwargs):
        ctx = super(IndexView, self).get_context_data(**kwargs)
        ctx['audio'] = ItemAudio.objects.all()
        ctx['document'] = ItemDocument.objects.all()
        return ctx
        
    
class DocumentView(generic.DetailView):
    template_name = 'portfolio/document.html'
    model = ItemDocument
    
class AudioView(generic.DetailView):
    template_name = 'portfolio/audio.html'
    model = ItemAudio

portfolio/templates/portfolio/audio.html
<!DOCTYPE html>
<html>
    <head>
        <title>Portfolio -- Paul Roylance</title>
        
        <link rel="stylesheet" type="text/css" href="/static/portfolio/style.css"/>
    </head>
    <body>
        <header class="cap">
            -- Paul E. Roylance -- Computer Engineering -- Utah State University --
        </header>
        <audio src="{{ itemaudio.embed_text }}" controls autoplay loop>
            Your browser does not support cool sounds. Lame.
        </audio>
        <div class="push"></div>
        <footer class="cap">
            <p>Contact me here -- grunzila@gmail.com</p>
        </footer>
    </body>
</html>

portfolio/templates/portfolio/document.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Portfolio -- Paul Roylance</title>
        <link rel="stylesheet" type="text/css" href="/static/portfolio/style.css"/>
    </head>
    <body>
        <!--Name-Occupation-Education-->
        <header class="cap">
            -- Paul E. Roylance -- Computer Engineering -- Utah State University --
        </header>
        <embed src="{{ itemdocument.embed_text }}" type="text/plain">
        <div class="push"></div>
        <footer class="cap">
            <p>Contact me here -- grunzila@gmail.com</p>
        </footer>
    </body>
</html>

portfolio/templates/portfolio/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Portfolio -- Paul Roylance</title>
        <script type="text/javascript" src="{% static 'portfolio/script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}"/>
    </head>
    <body>
        <header class="cap">
            -- Paul E. Roylance -- Computer Engineering -- Utah State University --
        </header>
        <div class="intro">
            <p>Portfolio:
            <br>Brag about yourself, they said. Really sell yourself, they said.
            <br>Should I even trust those voices? Probably. They have real jobs.
            <br>I will make this concise then. Ahem. *Bragging*</p>
        </div>
        <div class="blurb" id="blurb">
            <img class="inner_blurb" src="{% static 'portfolio/images/face.png' %}" alt="Profile Image" height="399" width="300">
            {% for words in object_list %}
            <div class="inner_blurb" id="words">{{ words.blurb_text }}</div>
            {% endfor %}
        </div>
        <div class="document_lead">
            <h2>documents</h2>
        </div>
        <div class="document">
            {% for doc in document %}
            <a href="{% url 'portfolio:document' doc.id %}" target="_blank">{{ doc.item_text }}</a>
            {% endfor %}
        </div>
        <div class="audio_lead">
            <h2>audiothings</h2>    
        </div>
        <div class="audio">
            {% for aud in audio %}
            <a href="{% url 'portfolio:audio' aud.id %}" target="_blank">{{ aud.item_text }}</a>
            {% endfor %}
        </div>
        <div class="final">
            <p>You can't fire me! Slaves gotta be sold.</p> 
        </div>
        <div class="push"></div>
        <footer class="cap">
            <p>Contact me here -- grunzila@gmail.com</p>
        </footer>
    </body>
</html>